language: node_js
node_js:
  - "0.10"

notifications:
  email:
    recipients:
      - martinmicunda@hotmail.com
    on_success: never
    on_failure: always

env:
  global:
    # travis-encrypt -r martinmicunda/mm-angular-logger -k COVERALLS_REPO_TOKEN -v <https://help.github.com/articles/creating-an-access-token-for-command-line-use> --add env.globa
#    - secure: YDGbgsTSvN9evJIRhX22Y+P56VYK50bT1tnQrkMxLRANyyQc6UF/e5iKWm+Yy4/0OWq12o+2tTvBc/MgdwSE+t28E+VmdF/JcQDY2pHb8szQ6PjS1PCkeq3IbYvdsYTSAWOBa9coqXECwkwEdtI6tuGQpXL/MOnq7ZncOetdpF4=

# starts xvfb on display port :99.0 (virtual display for Firefox)
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# install dependencies necessary to run this build
install:
  - npm install --quiet
  - bower install

script:
  - gulp test

